const clientList = [
  {
    id: 1,
    fname: 'Frank',
    lname: 'Beans',
    prefix: 'FB',
    isSyncing: false,
    reSyncData: false,
    covers: [
      {
        id: 1,
        name: 'Family Protection',
        amount: 50000,
        icon: 'fp',
      },
      {
        id: 2,
        name: 'Health Cover',
        amount: 11003,
        icon: 'hc',
      },
      {
        id: 3,
        name: 'Income Protection',
        amount: 11003,
        icon: 'ip',
      },
      {
        id: 4,
        name: 'Life cover',
        amount: 11003,
        icon: 'lc',
      },

      {
        id: 5,
        name: 'Mortgage Protection',
        amount: 11003,
        icon: 'mp',
      },

      {
        id: 6,
        name: 'Premium Waiver',
        amount: 11003,
        icon: 'pw',
      },

      {
        id: 7,
        name: 'Reduncy Cover',
        amount: 11003,
        icon: 'rc',
      },
      {
        id: 8,
        name: 'Trauma Cover',
        amount: 5000,
        icon: 'tc',
      },

      {
        id: 9,
        name: 'Total Permanent Disability',
        amount: 11003,
        icon: 'tpd',
      },
    ],
  },
  {
    id: 2,
    fname: 'Ryan',
    lname: 'Sandoval',
    prefix: 'RS',
    isSyncing: false,
    reSyncData: false,
    covers: [
      {
        id: 1,
        name: 'Family Protection',
        amount: 50000,
        icon: 'fp',
      },
      {
        id: 2,
        name: 'Health Cover',
        amount: 11003,
        icon: 'hc',
      },
      {
        id: 3,
        name: 'Income Protection',
        amount: 11003,
        icon: 'ip',
      },
      {
        id: 4,
        name: 'Life cover',
        amount: 11003,
        icon: 'lc',
      },

      {
        id: 5,
        name: 'Mortgage Protection',
        amount: 11003,
        icon: 'mp',
      },

      {
        id: 6,
        name: 'Premium Waiver',
        amount: 11003,
        icon: 'pw',
      },

      {
        id: 7,
        name: 'Reduncy Cover',
        amount: 11003,
        icon: 'rc',
      },
      {
        id: 8,
        name: 'Trauma Cover',
        amount: 5000,
        icon: 'tc',
      },

      {
        id: 9,
        name: 'Total Permanent Disability',
        amount: 11003,
        icon: 'tpd',
      },
    ],
  },
];

const insurerList = [
  {
    id: 1,
    providerName: 'AIA',
    providerNameLowerCases: 'aia',
    username: '',
    password: '',
    isConnected: true,
    isSyncing: false,
    message: '',
  },
  {
    id: 3,
    providerName: 'Fidelity',
    providerNameLowerCases: 'fidelity',
    username: '',
    password: '',
    isConnected: false,
    isSyncing: false,
    message: '',
  },
  {
    id: 4,
    providerName: 'Asteron Life',
    providerNameLowerCases: 'asteron_life',
    username: '',
    password: '',
    isConnected: true,
    isSyncing: false,
    message: '',
  },
  {
    id: 5,
    providerName: 'NIB',
    providerNameLowerCases: 'nib',
    username: '',
    password: '',
    isConnected: false,
    isSyncing: false,
    message: '',
  },
  {
    id: 6,
    providerName: 'Partners Life',
    providerNameLowerCases: 'partners_life',
    username: '',
    password: '',
    isConnected: false,
    isSyncing: false,
    message: '',
  },
  {
    id: 8,
    providerName: 'AMP',
    providerNameLowerCases: 'amp',
    username: '',
    password: '',
    isConnected: false,
    isSyncing: false,
    message: '',
  },
  {
    id: 9,
    providerName: 'Cigna',
    providerNameLowerCases: 'cigna',
    username: '',
    password: '',
    isConnected: false,
    isSyncing: false,
    message: '',
  },
  {
    id: 10,
    providerName: 'Southern Cross',
    providerNameLowerCases: 'southern_cross',
    username: '',
    password: '',
    isConnected: false,
    isSyncing: false,
    message: '',
  },
  {
    id: 11,
    providerName: 'Accuro',
    providerNameLowerCases: 'accuro',
    username: '',
    password: '',
    isConnected: false,
    isSyncing: false,
    message: '',
  },
];
